### ISSUE TITLE
Create persona/profile for lesson content

### ISSUE THREAD

**Issue by claremichaud** [carpentries-incubator/python-text-analysis#5]
<details>
Create a persona/profile to bring context to the workshop material and drives the content of the workshop with somewhat of a narrative
</details>

**Comment by caseyschacher** [comment]
-A researcher in the Sociology department wants to analyze the social media posts of major politicians in the United States to understand how often they are using "coded language", particularly as it pertains to race.  They have generated a list of potentially "coded" words and phrases, but want to identify more.  They also want to identify trends, if any, of who is using coded language (political party, position, race, age, gender, geographic location, etc.) as well as what contexts the language is being used most often.  They aren't quite sure which social media platforms to target, but believe twitter might be a good place to start.

**Comment by caseyschacher** [comment]
> 
> 
> -A researcher in the Sociology department wants to analyze the social media posts of major politicians in the United States to understand how often they are using "coded language", particularly as it pertains to race. They have generated a list of potentially "coded" words and phrases, but want to identify more. They also want to identify trends, if any, of who is using coded language (political party, position, race, age, gender, geographic location, etc.) as well as what contexts the language is being used most often. They aren't quite sure which social media platforms to target, but believe twitter might be a good place to start.

Opps!  I thought you wanted us to develop a variety of profiles for possible participants in the workshop so we could keep them in mind as we develop content.  Using profiles as a usability tool is common in web development so that is what I thought this meant.  But now I just saw the bit about you wanting us to create a single "profile" to drive the narrative of the lessons.  So please disregard my suggestion.  Feel free to delete.
